[build]
  command = "bun install && bun run prisma generate && bun run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  framework = "#custom"
  command = "bun run start"  
  targetPort = 3001          
  port = 8888               

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.0"