[build.environment]
  GH_TOKEN = ""

[build]
command = "git config --global url.\"https://${GH_TOKEN}@github.com\".insteadOf \"https://github.com\" && bun install && bun run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "bun run dev"
  port = 8888