[build]
  command = "bun install && bun run prisma generate && bun run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "bun run dev"
  port = 8888

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.0" # or latest version